// Generated by Claude Sonnet 4 on 2025-06-30 19:29 PDT.
// Jest setup file for global type definitions and configurations.

// This file ensures Jest globals are available in test files
import '@jest/globals';

// Configure Jest environment for ESM modules
import { jest, afterEach } from '@jest/globals';

// Global test timeout (30 seconds)
jest.setTimeout(30000);

// Suppress console logs during tests unless explicitly needed
const originalConsole = global.console;
global.console = {
  ...originalConsole,
  log: jest.fn(),
  info: jest.fn(),
  warn: jest.fn(),
  error: originalConsole.error, // Keep errors visible
};

// Reset console after each test
afterEach(() => {
  jest.clearAllMocks();
});
