// Generated by Claude Sonnet 4 on 2025-06-30 19:29 PDT.
// Jest setup file for global type definitions and configurations.

// This file ensures Jest globals are available in test files
import '@jest/globals';

// Configure Jest environment for ESM modules
import { jest, afterEach, beforeEach } from '@jest/globals';

// Global test timeout (10 seconds to prevent hanging)
jest.setTimeout(10000);

// Suppress console logs during tests unless explicitly needed
const originalConsole = global.console;
global.console = {
  ...originalConsole,
  log: jest.fn(),
  info: jest.fn(),
  warn: jest.fn(),
  error: originalConsole.error, // Keep errors visible
};

// Setup for each test
beforeEach(() => {
  // Clear any existing timers
  jest.clearAllTimers();
});

// Cleanup after each test
afterEach(() => {
  jest.clearAllMocks();
  jest.restoreAllMocks();
  // Force cleanup of any pending promises or timers
  jest.runOnlyPendingTimers();
  jest.clearAllTimers();
});

// Note: Jest handles cleanup automatically at the end of test runs.
// Using Jest APIs in process exit handlers can lead to unexpected behavior.
// All cleanup is properly handled by the afterEach hook above.
