#!/usr/bin/env node
// Generated by Claude Sonnet 4.0
/**
 * CLI Builder Tool - Command Line Interface
 * Entry point for the CLI application
 */

import { Command } from 'commander';
import chalk from 'chalk';
import { main } from './index.js';

const program = new Command();

program
  .name('copilot-instructions-builder')
  .description('A tool for building and managing CLI applications')
  .version('1.0.0');

program
  .command('init')
  .description('Initialize a new CLI project')
  .action(() => {
    console.log(chalk.green('🚀 Initializing CLI project...'));
    main();
  });

program
  .command('build')
  .description('Build the CLI project')
  .action(() => {
    console.log(chalk.blue('🔨 Building CLI project...'));
  });

// Parse command line arguments
program.parse();
